=== rishabhchand007/kb-store/catalog_20048980.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!-- 
Name: Rishabh Chand 
London Met ID: 20048980
d: 
-->

<!--This XSD file describes nad validates the structure and content of the catalog_20048980 XML file.
  Salami Slice design is used in this XSD File,  in this design we disassemble the instance document into its various components. 
  We specify each component in the schema and then put them together.
-->

<xs:element name="country" type="xs:string"/>
<xs:element name="city" type="xs:string"/>
<xs:element name="name" type="xs:string"/>
<xs:element name="address">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="country"/>
      <xs:element ref="city"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!--Restriction is used to define acceptable values in the XSD.
Below, MinInclusive and MaxInclusive is used to define maximum and minimum value accepted in the element-->

<xs:element name="telephone_number" >
  <xs:simpleType>
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="9999999"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<!--anyURI is contains only URI of any site-->
<xs:element name="url" type="xs:anyURI"/>


<xs:element name="logo">
  <xs:complexType>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:element>
<xs:element name="a">
  <xs:complexType>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <!--IF NO DATA IS INSERTED IN THE ATTRIBUTE IT IS AUTOMATICALLY SET TO '#home'-->
        <xs:attribute type="xs:string" name="href" use="optional" default="#home"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:element>
<xs:element name="li">
  <xs:complexType mixed="true">
    <xs:sequence>
      <xs:element ref="a" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
<xs:element name="ul">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="li" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
<xs:element name="searchbox" type="xs:string"/>
<xs:element name="store_details">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="name"/>
      <xs:element ref="address"/>
      <xs:element ref="telephone_number"/>
      <xs:element ref="url"/>
      <xs:element ref="logo"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
<xs:element name="links">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="ul"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
<xs:element name="search">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="searchbox"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
<xs:element name="title" type="xs:string"/>
<xs:element name="image">
  <xs:complexType>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:element>
<xs:element name="card_name" type="xs:string"/>
<xs:element name="cost" >
  <xs:simpleType>
    <xs:restriction base="xs:positiveInteger" >
      <xs:minInclusive value="1"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name="supplier" >
  <xs:simpleType>
    <!--ENUMERATION DESCRIBES ONLY VALUES THAT CAN BE STORED IN THE ELEMENT-->
  <xs:restriction base="xs:string">
    <xs:enumeration value="Apple"/>
    <xs:enumeration value="Amazon"/>
    <xs:enumeration value="Spotify"/>
    <xs:enumeration value="Steam"/>
    <xs:enumeration value="Nintendo"/>
    <xs:enumeration value="Xbox"/>
    <xs:enumeration value="PS"/>
    <xs:enumeration value="Netflix"/>
    <xs:enumeration value="Epic Games"/>
    <xs:enumeration value="Google"/>
    <xs:enumeration value="Microsoft"/>
  </xs:restriction>
</xs:simpleType>
</xs:element>
<xs:element name="validity" >
  <xs:simpleType>
    <!--positiveInteger datatype only accepts positive integer values -->
    <xs:restriction base="xs:positiveInteger">
      <!--Patterns describes the patten in which data is placed in the element-->
      <xs:pattern value="[0-9][0-9][0-9][0-9]"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="stock" type="xs:string"/>
<xs:element name="info" type="xs:string"/>
<xs:element name="purchase_btn">
  <xs:complexType>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <!-- FIXED CONTAINS THE ONLY DATA THAT IS ACCEPTED IN THE ATTRIBUTE-->
        <xs:attribute type="xs:string" name="notAvailable" fixed="no"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:element>
<xs:element name="discount" >
  <xs:simpleType>
    <xs:restriction base="xs:positiveInteger">

      <xs:maxInclusive value="90"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name="delivery" type="xs:string"/>
<xs:element name="gift_card">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="image" maxOccurs="1" minOccurs="1"/>
      <xs:element ref="card_name" maxOccurs="1" minOccurs="1"/>
      <xs:element ref="cost" maxOccurs="1" minOccurs="1"/>
      <xs:element ref="supplier" maxOccurs="1" minOccurs="1"/>
      <xs:element ref="validity" minOccurs="0"/>
      <xs:element ref="stock" minOccurs="0"/>
      <xs:element ref="discount" minOccurs="0"/>
      <xs:element ref="info" minOccurs="0"/>
      <xs:element ref="delivery" minOccurs="0"/>
      <xs:element ref="purchase_btn"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:string" name="type" use="required"/>
    <xs:attribute  name="category" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:enumeration value="Purchase"/>
            <xs:enumeration value="Gaming"/>
            <xs:enumeration value="Music"/>
            <xs:enumeration value="Video"/>
            <xs:enumeration value="Gift"/>
        </xs:restriction>
    </xs:simpleType>
    </xs:attribute>
    <xs:attribute type="xs:string" name="class" use="optional"/>
  </xs:complexType>
</xs:element>
<xs:element name="div">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="title"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="optional"/>
  </xs:complexType>
</xs:element>
<xs:element name="products">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="gift_card" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
<xs:element name="featured">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="div"/>
      <xs:element ref="products"/>
    </xs:sequence>
    <xs:attribute type="xs:byte" name="row_number"/>
  </xs:complexType>
</xs:element>
<xs:element name="row">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="div" minOccurs="0"/>
      <xs:element ref="products"/>
    </xs:sequence>
    <xs:attribute type="xs:byte" name="row_number" use="optional"/>
  </xs:complexType>
</xs:element>
<xs:element name="nav">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="store_details"/>
      <xs:element ref="links"/>
      <xs:element ref="search"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
<xs:element name="cards">
  <xs:complexType>
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element ref="featured"/>
      <xs:element ref="row"/>
    </xs:choice>
  </xs:complexType>
</xs:element>
<xs:element name="p" type="xs:string"/>
<xs:element name="help">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="title"/>
      <xs:element ref="p" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
<xs:element name="socials">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="logo" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id"/>
  </xs:complexType>
</xs:element>
<xs:element name="header">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="nav"/>
      <xs:element ref="cards"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
<xs:element name="footer">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="help"/>
      <xs:element ref="ul"/>
      <xs:element ref="socials"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
<xs:element name="store">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="header"/>
      <xs:element ref="footer"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== rishabhchand007/kb-store/index.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
Name: Rishabh Chand 
London Met ID: 20048980

Description: An XML Page is developed for KB Gift Card store which sells Digital and Physical gift cards.
Each  Gift card has a number of information which is maintained and displayed in a template card.
-->
<?xml-stylesheet type="text/css" href="style.css"?>
<store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
xsi:noNamespaceSchemaLocation="catalog_20048980.xsd">
    <header>
        <!-- The header section contains navigation bar and main section of the webpage -->
        <nav>
            <!-- The navigatio contains store details, links to different pages and a search box -->
            <store_details>
                <!--this elements contains all the information of the store-->
                <name>KB Gift Cards</name>
                <address>
                    <country>United Kingdom</country>
                    <city>London</city>
                </address>
                <telephone_number>00976538</telephone_number>
                <url>www.kbgiftcards.com.np</url>
                <logo></logo>
            </store_details>
            <links>
                <!-- This contains navigation bar links -->
                <ul>
                    <li>
                        <a href="">Home</a>
                    </li>
                    <li>
                        <a href="">Product</a>
                    </li>
                    <li>
                        <a href="">Contact</a>
                    </li>
                    <li>
                        <a href="">About</a>
                    </li>
                </ul>
            </links>
            <search>
                <!-- This contains search bar for the navigation bar -->
                <searchbox></searchbox>
            </search>
        </nav>

         
        <cards>
           <!-- cards element contains all the rows which contains gift card details -->
            <featured row_number="1">
                <!-- Featured row contains details of all the featured gift cards -->
                <div id="h1">
                    <title>Featured</title>
                </div>
                <products>
                    <gift_card id="gc1" type="Digital" category="Music" class="Featured ">
                    <!-- Details of the gift card -->
                        <image id="apple90"></image>
                        <card_name>Apple Gift Card</card_name>
                        <cost>5500</cost>
                        <supplier>Apple</supplier>
                        <validity>2024</validity>
                        <stock>Available: 16</stock>
                        <info>Cannot Be Returned!</info>
                        <purchase_btn>Buy Now</purchase_btn>
                    </gift_card>

                    <gift_card id="gc2" type="Physical" category="Gift" class="Featured">
                        <!-- Details of the gift card -->
                        <image id="Visa"></image>
                        <card_name>Visa Happy B-Day Gift Card</card_name>
                        <cost>3500</cost> 
                        <supplier>Amazon</supplier>
                        <validity>2024</validity>
                        <stock>Available: 34</stock>
                        <purchase_btn>Buy Now</purchase_btn>
                    </gift_card>
                    
                    <gift_card id="gc3" type="Digital" category="Purchase" class="Featured">
                        <!-- Details of the gift card -->
                        <image id="spotify"></image>
                        <card_name>Spotify $10</card_name>
                        <cost>1500</cost>
                        <supplier>Spotify</supplier>
                        <validity>2024</validity>
                        <discount>5</discount>
                        <info>Discount only for IME pay payments</info>
                        
                        <purchase_btn>Buy Now</purchase_btn>
                    </gift_card>


                    <gift_card id="gc4" type="Digital" category="Gaming" class="Featured">
                        <!-- Details of the gift card -->
                        <image id="steam"></image>
                        <card_name>Steam Wallet Code</card_name>
                        <cost>12000</cost>
                        <supplier>Steam</supplier>
                        <discount>10</discount>
                        <delivery>Instant Delivery!</delivery>
                        <purchase_btn notAvailable="no" >Out of Stock</purchase_btn>
                    </gift_card>
                </products>
            </featured>
            <row row_number="2">
                <!-- This contains card details of second row -->
                <div id="h1">
                    <title>ALL PRODUCTS</title>
                </div>
                <products>
                    <gift_card id="gc5" type="Physical" category="Gaming" >
                        <!-- Details of the gift card -->
                        <image id="nintendo"></image>
                        <card_name>NS Family Membership</card_name>
                        <cost>4500</cost>
                        <supplier>Nintendo</supplier>
                        <validity>2026</validity>
                        <delivery>Instant Delivery!</delivery>
                        
                        <purchase_btn>Buy Now</purchase_btn>
                        
                    </gift_card>

                    <gift_card id="gc6" type="Digital" category="Gaming">
                        <!-- Details of the gift card -->
                        <image id="xbox"></image>
                        <card_name>Xbox Game Pass Ultimate</card_name>
                        <cost>6000</cost> 
                        <supplier>Xbox</supplier>
                        <stock>Available: 100</stock>
                        <purchase_btn>Buy Now</purchase_btn>
                    </gift_card>

                    <gift_card id="gc7" type="Physical" category="Gaming" >
                        <!-- Details of the gift card -->
                        <image id="playstation"></image>
                        <card_name>Playstation Gift Card</card_name>
                        <cost>3500</cost>
                        <supplier>PS</supplier>
                        <validity>2024</validity>
                        <info>No Refund</info>
                        <purchase_btn>Buy Now</purchase_btn>
                    </gift_card>


                    <gift_card id="gc8" type="Digital" category="Video" >
                        <!-- Details of the gift card -->
                        <image id="netflix"></image>
                        <card_name>Netflix Gift Card</card_name>
                        <cost>2700</cost>
                        <supplier>Netflix</supplier>
                        <validity>2025</validity>
                        <discount>5</discount>
                        <purchase_btn>Buy Now</purchase_btn>
                    </gift_card>
                    
                </products>
            </row>
            <row row_number="3">
                <!-- Contains Details of cards of 3rd row  -->
                <products>
                    <gift_card id="gc9" type="Physical" category="Purchase" >
                        <!-- Details of the gift card -->
                        <image id="googleplay"></image>
                        <card_name>Google Play Gift Card</card_name>
                        <cost>5700</cost>
                        <supplier>Google</supplier>
                        <discount>10</discount>
                        <info>Discount only for IME Pay Payments</info>
                        <purchase_btn>Buy Now</purchase_btn>
                        
                    </gift_card>

                    <gift_card id="gc10" type="Physical" category="Purchase">
                        <!-- Details of the gift card -->
                        <image id="amazon"></image>
                        <card_name>Amazon Gift Card</card_name>
                        <cost>5800</cost> 
                        <supplier>Amazon</supplier>
                        <validity>2024</validity>
                        <stock>Available: 120</stock>
                        <purchase_btn>Buy Now</purchase_btn>
                    </gift_card>

                    <gift_card id="gc11" type="Physical" category="Gaming" >
                        <!-- Details of the gift card -->
                        <image id="fortnite"></image>
                        <card_name>Fortnite V-Bucks Gift Card</card_name>
                        <cost>3800</cost>
                        <supplier>Epic Games</supplier>
                        <discount>10</discount>
                        <info>No Refund</info>
                        <purchase_btn>Buy Now</purchase_btn>
                    </gift_card>


                    <gift_card id="gc12" type="Digital" category="Gaming">
                        <!-- Details of the gift card -->
                        <image id="steam5"></image>
                        <card_name>Steam Gift Card $50</card_name>
                        <cost>5700</cost>
                        <supplier>Steam</supplier>
                        <validity>2023</validity>
                        <discount>10</discount>
                        <delivery>Instant Delivery</delivery>
                        <purchase_btn>Buy Now</purchase_btn>
                    </gift_card>
                    
                </products>
            </row>

            <row row_number="4">
                <!-- Contains Details of cards of 4th row  -->
                
                <products>
                    <gift_card id="gc13" type="Physical" category="Video" >
                        <!-- Details of the gift card -->
                        <image id="netflix6"></image>
